src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SortieRepository::class)]
class Sortie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDateTime = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $duration = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $registrationDeadLine = null;

    #[ORM\Column]
    private ?int $registrationNumberMax = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $information = null;

    #[ORM\ManyToOne]
    #[ORM\Column(nullable: false)]
    private ?Etat $State = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartDateTime(): ?\DateTimeInterface
    {
        return $this->startDateTime;
    }

    public function setStartDateTime(\DateTimeInterface $startDateTime): self
    {
        $this->startDateTime = $startDateTime;

        return $this;
    }

    public function getDuration(): ?\DateTimeInterface
    {
        return $this->duration;
    }

    public function setDuration(\DateTimeInterface $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getRegistrationDeadLine(): ?\DateTimeInterface
    {
        return $this->registrationDeadLine;
    }

    public function setRegistrationDeadLine(\DateTimeInterface $registrationDeadLine): self
    {
        $this->registrationDeadLine = $registrationDeadLine;

        return $this;
    }

    public function getRegistrationNumberMax(): ?int
    {
        return $this->registrationNumberMax;
    }

    public function setRegistrationNumberMax(int $registrationNumberMax): self
    {
        $this->registrationNumberMax = $registrationNumberMax;

        return $this;
    }

    public function getInformation(): ?string
    {
        return $this->information;
    }

    public function setInformation(?string $information): self
    {
        $this->information = $information;

        return $this;
    }

    public function getState(): ?Etat
    {
        return $this->State;
    }

    public function setState(?Etat $State): self
    {
        $this->State = $State;

        return $this;
    }
}

src/Form/TripType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Spot;
use App\Entity\Trip;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class TripType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la sortie : '
            ])
            ->add('startDateTime', DateTimeType::class, [
                'label' => 'Date et heure de la sortie : ',
                'widget' => 'single_text',
                'model_timezone' => 'Europe/Paris',
            ])
            ->add('registrationDeadLine', DateType::class, [
                'label' => 'Date limite d\'inscription',
                'widget' => 'single_text',
                'model_timezone' => 'Europe/Paris'
            ])
            ->add('registrationNumberMax', TextType::class, [
                'label' => 'Nombre de places : '
            ])
            ->add('duration', IntegerType::class, [
                'label' => 'Durée : ',
                'attr' => [
                    'placeholder' => 'en minutes'
                ]
            ])
            ->add('information', TextareaType::class, [
                'label' => 'Description et infos : '
            ])
            ->add('campus', EntityType::class, [
                'label' => 'Campus : ',
                'class' => Campus::class,
                'placeholder' => '-- Choisissez un campus --',
                'choice_label' => 'name'
            ])
            ->add('spot', EntityType::class, [
                'label' => 'Lieu : ',
                'class' => Spot::class,
                'placeholder' => '-- Choisissez un lieu --',
                'choice_label' => 'name',
                'required' => false
            ])
            ->add('spot1', SpotType::class, [
                'mapped' => false,
                'label' => null,
                'required' => false
            ])
            ->add('create', SubmitType::class, [
                'label' => 'Enregistrer'
            ])
            ->add('publish', SubmitType::class, [
                'label' => 'Publier la sortie'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trip::class
        ]);
    }
}

src/Controller/TripController.php
<?php

namespace App\Controller;


use App\Data\SearchData;
use App\Entity\Trip;
use App\Form\CancelType;
use App\Form\SearchType;
use App\Form\TripType;
use App\Repository\CampusRepository;
use App\Repository\SpotRepository;
use App\Repository\StateRepository;
use App\Repository\TripRepository;
use App\Service\LifeCycleTripService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route('/', name: 'trip_')]
class TripController extends AbstractController
{
    #[Route('/creer-une-sortie', name: 'create')]
    public function create(EntityManagerInterface $entityManager, Request $request, StateRepository $stateRepository): Response
    {
        $trip = new Trip();
        $trip->setPromoter($this->getUser());

        $tripForm = $this->createForm(TripType::class, $trip);
        $tripForm->handleRequest($request);

        if ($tripForm->isSubmitted() && $tripForm->isValid()) {
            $spot = $tripForm->get('spot1')->getData();

            if ($spot->getName()) {
                $trip->setSpot($spot);
            }

            if ($tripForm->get('create')->isClicked()) {
                $trip->setState($stateRepository->find(1));
            } elseif ($tripForm->get('publish')->isClicked()) {
                $trip->setState($stateRepository->find(2));
            }

            $trip->addUser($this->getUser());

            $entityManager->persist($trip);
            $entityManager->flush();

            $this->addFlash('success', 'La sortie a été créée.');
            return $this->redirectToRoute('trip_list');
        }

        return $this->render('trip/create.html.twig', [
            'tripForm' => $tripForm->createView()
        ]);
    }


    #[Route('/modifier-une-sortie/{id}', name: 'updateTrip')]
    public function updateTrip(EntityManagerInterface $manager, Request $request, TripRepository $tripRepository, int $id, StateRepository $stateRepository, SpotRepository $spotRepository): Response
    {

        $trip = $tripRepository->find($id);
        $user = $this->getUser();

        $tripUpdateForm = $this->createForm(TripType::class, $trip);
        $tripUpdateForm->handleRequest($request);

        if ($trip->getState()->getWording() === "En Création" and $trip->getPromoter() === $user) {

            if ($tripUpdateForm->isSubmitted() && $tripUpdateForm->isValid()) {
                $spot = $tripUpdateForm->get('spot1')->getData();

                if ($spot->getName()) {
                    $trip->setSpot($spot);
                }

                if ($tripUpdateForm->get('create')->isClicked()) {
                    $trip->setState($stateRepository->find(1));
                } elseif ($tripUpdateForm->get('publish')->isClicked()) {
                    $trip->setState($stateRepository->find(2));
                }

                $manager->persist($trip);
                $manager->flush();

                $this->addFlash('success', 'La sortie a été modifiée.');
                return $this->redirectToRoute('trip_list');
            }

        } else {

            $this->addFlash('error', 'La sortie ne peut pas être modifiée');
            return $this->redirectToRoute('trip_list');
        }

        return $this->render('trip/update.html.twig', [
            'tripForm' => $tripUpdateForm->createView(),
            'trip' => $trip
        ]);
    }



    #[Route('', name: 'list')]
    public function list(TripRepository $tripRepository, CampusRepository $campusRepository, LifeCycleTripService $cycleTripService, Request $request): Response
    {
        $data = new SearchData();
        $searchForm = $this->createForm(SearchType::class, $data);
        $searchForm->handleRequest($request);
        $trips = $tripRepository->findSearch($data, $this->getUser());

        $cycleTripService->lifeCycleTrip();

        $campus = $campusRepository->findAll();

        return $this->render('trip/list.html.twig', [
            'trips' => $trips,
            'campus' => $campus,
            'searchForm' => $searchForm->createView()
        ]);
    }

    #[Route('/detail/{id}', name: 'detail')]
    public function detail(int $id, TripRepository $tripRepository): Response
    {
        $trip = $tripRepository->find($id);
        $users = $trip->getUsers();

        return $this->render('trip/detail.html.twig', [
            'trip' => $trip,
            'users' => $users
        ]);
    }

    #[Route('/publish/{id}', name: 'publish')]
    public function publish(EntityManagerInterface $entityManager, StateRepository $stateRepository, TripRepository $tripRepository, int $id): Response {
        $user = $this->getUser();
        $trip = $tripRepository->find($id);

        if ($trip->getState()->getWording() === "En Création" and $trip->getPromoter() === $user) {
            $trip->setState($stateRepository->find(2));

            $entityManager->persist($trip);
            $entityManager->flush();
        } else {
            $this->addFlash('error', 'Tu nous aura pas comme ça Sylvain :)');
        }

        return $this->redirectToRoute('trip_list');
    }

    #[Route('/delete/{id}', name: 'delete')]
    public function delete(EntityManagerInterface $entityManager, TripRepository$tripRepository, int $id) {
        $user = $this->getUser();
        $trip = $tripRepository->find($id);

        if ($trip->getState()->getWording() === "En Création" and $trip->getPromoter() === $user) {
            $entityManager->remove($trip);
            $entityManager->flush();

            $this->addFlash('success', 'La sortie a bien été supprimé');
        } else {
            $this->addFlash('error', 'Tu nous aura pas comme ça Sylvain :)');
        }

        return $this->redirectToRoute('trip_list');
    }

    #[Route('/cancel/{id}', name: 'cancel')]
    public function cancel(EntityManagerInterface $entityManager, StateRepository $stateRepository, TripRepository $tripRepository, int $id, Request $request, CampusRepository $campusRepository): Response {
        $trip = $tripRepository->find($id);
        $user = $this->getUser();

        $cancelForm = $this->createForm(CancelType::class, $trip);
        $cancelForm->handleRequest($request);

        if ($trip->getState()->getWording() === "Ouverte" and $trip->getPromoter() === $user){
            if ($cancelForm->isSubmitted() && $cancelForm->isValid()) {
                $trip->setState($stateRepository->find(4));

                if ($trip->getState()->getWording() == "Ouverte") {
                    $entityManager->persist($trip);
                    $entityManager->flush();

                    $this->addFlash("success", "La sortie a bien été annulée");
                    return $this->redirectToRoute('trip_list');

                } else {
                    $this->addFlash('error', 'La sortie ne peut plus être annulée');
                }
            }
        } else {
            $this->addFlash('error', 'Tu nous aura pas comme ça Sylvain :)');
            return $this->redirectToRoute('trip_list');
        }


        return $this->render('trip/cancel.html.twig', [
            'cancelForm' => $cancelForm->createView(),
            'trip' => $trip
        ]);
    }

    #[Route('/sortie-annulee/{id}', name: 'cancelDetail')]
    public function cancelDetail(TripRepository $tripRepository, int $id): Response {
        $trip = $tripRepository->find($id);

        return $this->render('trip/cancelDetail.html.twig', [
            'trip' => $trip
        ]);
    }

    #[Route('/subscribeTrip/{id}', name: 'subscribeTrip')]
    public function subscribeTrip(EntityManagerInterface $entityManager, TripRepository $tripRepository, int $id, StateRepository $stateRepository): Response
    {
        $trip = $tripRepository->find($id);

        $user = $this->getUser();

        if ($trip->getUsers()->count() < $trip->getRegistrationNumberMax() and $trip->getState()->getWording() === "Ouverte") {

            $trip->addUser($user);

            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('success', 'Vous êtes bien inscrit à la sortie : '.$trip->getName());
        } else {
            $this->addFlash('error', 'Tu nous aura pas comme ça Sylvain :)');
        }

        if ($trip->getUsers()->count() === $trip->getRegistrationNumberMax()) {
            $trip->setState($stateRepository->find(3));

            $entityManager->persist($trip);
            $entityManager->flush();
        }

        return $this->redirectToRoute('trip_list');
    }

    #[Route('/unsubscribeTrip/{id}', name: 'unsubscribeTrip')]
    public function unsubscribeTrip(EntityManagerInterface $entityManager, TripRepository $tripRepository, int $id, StateRepository $stateRepository): Response
    {
        $trip = $tripRepository->find($id);

        $user = $this->getUser();
        $dateNow = new \DateTime("now");

        if ($trip->getStartDateTime() >= $dateNow and $trip->getUsers()->contains($user)) {
            $trip->removeUser($user);

            $entityManager->persist($user);
            $entityManager->flush();

            if ($trip->getUsers()->count() != $trip->getRegistrationNumberMax()) {
                $trip->setState($stateRepository->find(2));

                $entityManager->persist($trip);
                $entityManager->flush();
            }

            $this->addFlash('success', 'Vous vous êtes desisté de la sortie : '.$trip->getName());
        } else {
            $this->addFlash('error', 'Tu nous aura pas comme ça Sylvain :)');
        }



        return $this->redirectToRoute('trip_list');
    }
}

templates/trip/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Annuler une sortie
{% endblock %}

{% block body %}
    <h2>Annuler une sortie</h2>
    <p>Nom de la sortie : {{ trip.name }}</p>
    <p>Date de la sortie : {{ trip.startDateTime | date('d-m-Y') }}</p>
    <p>Campus : {{ trip.campus.name }}</p>
    <p>Lieu : {{ trip.spot.name }}</p>
    {{ form_start(cancelForm) }}
    {{ form_widget(cancelForm) }}
    <button type="submit" class="btn btn-primary">Annuler la sortie</button>
    <a href="{{ path('trip_list') }}" class="btn btn-secondary">Retour</a>
    {{ form_end(cancelForm) }}
{% endblock %}

templates/trip/cancelDetail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Sortie Annulée
{% endblock %}

{% block body %}
    <h2>Sortie Annulée</h2>
    <p>Nom de la sortie : {{ trip.name }}</p>
    <p>Date de la sortie : {{ trip.startDateTime | date('d-m-Y') }}</p>
    <p>Campus : {{ trip.campus.name }}</p>
    <p>Motif d'annulation : {{ trip.cancelMessage }}</p>
{% endblock %}

templates/trip/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h2>Créer une sortie</h2>
    <div class="row">
        <div class="col-md-12">
            {{ form_start(tripForm) }}

            <div class="row">
                <div class="col-md-6">
                    {{ form_row(tripForm.name) }}
                </div>
                <div class="col-md-6">

                    {{ form_row(tripForm.duration) }}
                </div>
                <div class="col-md-6">

                    {{ form_row(tripForm.startDateTime) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(tripForm.campus) }}
                </div>

            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ form_row(tripForm.registrationDeadLine) }}
                </div>
                <div class="col-md-6 ">
                    {{ form_row(tripForm.spot1.city) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(tripForm.registrationNumberMax) }}
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-10">
                            {{ form_row(tripForm.spot) }}
                        </div>
                        <div class="col pt-3">
                            <i class="plus fa-solid fa-circle-plus" data-bs-toggle="modal" data-bs-target="#spotModal"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    {{ form_row(tripForm.information) }}
                </div>

            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="spotModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Créer un Lieu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form_row(tripForm.spot1) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Ajouter un Lieu</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                </div>
            </div>
        </div>
    </div>

    <div style="
    justify-content: space-between;
    display: flex;">
        <div class="col">
            {{ form_row(tripForm.create) }}
        </div>
        <div class="col ">
            {{ form_row(tripForm.publish) }}
        </div>
        <div class="col">
            <a href="{{ path('trip_list') }}" class="btn btn-secondary">Annuler</a>
        </div>
    </div>

    {{ form_end(tripForm) }}

{% endblock %}

{% block title %}
Créer une Sortie
{% endblock %}

templates/trip/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h2>Afficher</h2>
    <div class="trip-info">
        <div class="left-column">
            <p><b>Nom de la Sortie</b> : {{ trip.name }}</p>
            <p><b>Date et heure de la sortie</b> : {{ trip.startDateTime | date('d-m-Y H:i') }}</p>
            <p><b>Date limite d'inscription</b> : {{ trip.registrationDeadLine | date('d-m-Y') }}</p>
            <p><b>Nombre de places</b> : {{ trip.registrationNumberMax }}</p>
            <p><b>Durée</b> : {{ trip.duration }} minutes</p>
            <p><b>Description</b> : {{ trip.information }}</p>
        </div>
        <div class="right-column">
            <p><b>Etat</b> : {{ trip.state.wording }}</p>
            <p><b>Campus</b> : {{ trip.campus.name }}</p>
            <p><b>Lieu</b> : {{ trip.spot.name }}</p>
            <p><b>Rue</b> : {{ trip.spot.street }}</p>
            <p><b>Code postal</b> : {{ trip.spot.city.zipCode }}</p>
            <p><b>Latitude</b> : {{ trip.spot.latitude }}</p>
            <p><b>Longitude</b> : {{ trip.spot.longitude }}</p>
        </div>
    </div>

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Pseudo</th>
            <th scope="col">Nom</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td><a href="{{ path('user_profile', {'name': user.name}) }}">{{ user.nickname }}</a></td>
                <td>{{ user.firstname }} {{ user.name | upper }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block title %}
    Detail de la Sortie
{% endblock %}

templates/trip/filterForm.html.twig
<div class="row">
    <div class="col-md-7">
        {{ form_start(searchForm) }}
        {{ form_row(searchForm.campus) }}
        {{ form_row(searchForm.keyWord) }}
        <div class="row">
            <div class="col-md-6">
                {{ form_row(searchForm.dateFrom) }}
            </div>
            <div class="col-md-6">
                {{ form_row(searchForm.dateTo) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                {{ form_row(searchForm.isPromoter) }}
                {{ form_row(searchForm.isSub) }}
            </div>
            <div class="col-md-6">
                {{ form_row(searchForm.isntSub) }}
                {{ form_row(searchForm.isTripEnd) }}
            </div>
        </div>

        <button type="submit" class="btn btn-dark">Rechercher</button>
        {{ form_end(searchForm) }}
    </div>
</div>

templates/trip/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Filtrer les sorties</h2>

    {% include 'trip/filterForm.html.twig'%}

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Nom de la sortie</th>
            <th scope="col">Date de la sortie</th>
            <th scope="col">Clôture</th>
            <th scope="col">Inscrits/Places</th>
            <th scope="col">Etat</th>
            <th scope="col">Inscrit</th>
            <th scope="col">Organisateur</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>

        {% for trip in trips %}
            {% if  trip.state.wording != "Activité Historisée" %}
                {% if trip.state.wording != "En Création" or trip.promoter.id == app.user.id %}
                    <tr>
                        <td>{{ trip.name }}</td>
                        <td>{{ trip.startDateTime | date('d-m-Y H:i') }}</td>
                        <td>{{ trip.registrationDeadLine | date('d-m-Y') }}</td>
                        <td>{{ trip.users | length }} / {{ trip.registrationNumberMax }}</td>
                        <td>{{ trip.state.wording }}</td>
                        {% if trip.users.contains(app.user) %}
                            <td><i class="check fa-solid fa-check"></i></td>
                        {% else %}
                            <td></td>
                        {% endif %}
                        <td><a href="{{ path('user_profile', {'name': trip.promoter.name}) }}">{{ trip.promoter.name }}</a></td>

                        {% if app.user.id == trip.promoter.id and trip.state.wording == "En Création" %}
                            <td><a href="{{ path('trip_updateTrip', {'id': trip.id}) }}">Modifier</a> - <a href="{{ path('trip_publish', {'id': trip.id}) }}">Publier</a></td>
                        {% elseif app.user.id == trip.promoter.id and trip.state.wording == "Ouverte" %}
                            <td><a href="{{ path('trip_detail', {'id': trip.id}) }}">Afficher</a> - <a href="{{ path('trip_cancel', {'id': trip.id}) }}">Annuler</a></td>
                        {% elseif trip.state.wording == "Annulée"  %}
                            <td><a href="{{ path('trip_cancelDetail', {'id': trip.id}) }}">Afficher</a>
                        {% elseif trip.state.wording == "Activité en cours" or trip.state.wording == "Activité Terminée"%}
                            <td><a href="{{ path('trip_detail', {'id': trip.id}) }}">Afficher</a>
                        {% elseif not trip.users.contains(app.user) %}
                            <td><a href="{{ path('trip_detail', {'id': trip.id}) }}">Afficher</a> - <a href="{{ path('trip_subscribeTrip', {'id': trip.id}) }}">S'inscrire</a></td>
                        {% else %}
                            <td><a href="{{ path('trip_detail', {'id': trip.id}) }}">Afficher</a> - <a href="{{ path('trip_unsubscribeTrip', {'id': trip.id}) }}">Se désister</a></td>
                        {% endif %}

                    </tr>
                {% endif %}
            {% endif %}
        {% endfor %}

        </tbody>
    </table>

    <a href="{{ path('trip_create') }}" class="btn btn-primary">Créer une sortie</a>
{% endblock %}

{% block title %}
    Liste des Sorties
{% endblock %}

templates/trip/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h2>Modifier une sortie</h2>
    <div class="row">
        <div class="col-md-12">
            {{ form_start(tripForm) }}

            <div class="row">
                <div class="col-md-6">
                    {{ form_row(tripForm.name) }}
                </div>
                <div class="col-md-6">

                    {{ form_row(tripForm.duration) }}
                </div>
                <div class="col-md-6">

                    {{ form_row(tripForm.startDateTime) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(tripForm.campus) }}
                </div>

            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ form_row(tripForm.registrationDeadLine) }}
                </div>
                <div class="col-md-6 ">
                    {{ form_row(tripForm.spot1.city) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(tripForm.registrationNumberMax) }}
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-10">
                            {{ form_row(tripForm.spot) }}
                        </div>
                        <div class="col pt-3">
                            <i class="plus fa-solid fa-circle-plus" data-bs-toggle="modal" data-bs-target="#spotModal"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    {{ form_row(tripForm.information) }}
                </div>

            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="spotModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Créer un Lieu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form_row(tripForm.spot1) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Ajouter un Lieu</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                </div>
            </div>
        </div>
    </div>

    <div style="
         justify-content: space-between;
         display: flex;">
        <div class="col">
            {{ form_row(tripForm.create) }}
        </div>
        <div class="col">
            {{ form_row(tripForm.publish) }}
        </div>
        <div class="col">
            <a href="{{ path('trip_delete', {'id': trip.id}) }}" class="btn btn-danger">Supprimer la sortie</a>
        </div>
        <div class="col">
            <a href="{{ path('trip_list') }}" class="btn btn-secondary">Annuler</a>
        </div>
    </div>

    {{ form_end(tripForm) }}

{% endblock %}

{% block title %}
    Modifier une Sortie
{% endblock %}